### PR TITLE
Asterion Launcher - FML 1.3.2 Classloader Fix

### PR DESCRIPTION
**Pull request by Theleruby**
As per e-mail requests from Dalton Pelc and Kurt H, I am submitting the following fix for Technic Launcher which provides compatibility with Forge Mod Loader 3.x+ (Minecraft 1.3+).

(Some credit would be nice somewhere if possible)

Thanks

### CODE REVIEW

**Comment by Salynne** [comment]
Thanks. I'll test this pull out locally soon and if it's good to go I'll commit it.

In git, your credit will permanently exist in the contributors list and the git blames which show who contributed what code.
https://github.com/Tinytimrob/Spoutcraft-Launcher/graphs/contributors

**Comment by ruifung** [comment]
It works all right, I just tested it. Forge 4.x starts and loads just fine.

**Comment by Salynne** [comment]
Thanks again. If you notice it now looks as if you directly committed to the project, forever https://github.com/TechnicPack/Spoutcraft-Launcher/commits/master

Hopefully that is credit enough :)

**Comment by Theleruby** [comment]
Thank you, that's great :)

**Pull request merged**
