### PR TITLE
Attempt to cleanup the pom.xml for now.

### PR DESCRIPTION
**Pull request by ghost**
Also added a small entry to the .gitignore file.

I see that you are trying to get synced with the upstream Spoutcraft project. So did won't merge with the `dev` branch.

But I wanted to share my hard work over the couple of days :P Just use it as reference. I'm able to compile the OS X version now. And it runs just fine. Maybe I will take a look at the Windows version if desired.

### CODE REVIEW

**Comment by luisantonioa** [comment]
Can you adjust it for the current version? It seems i had to resync my changes over the last month with github.. then it should be good to merge..

**Comment by ghost** [comment]
Just headed for bed, but I'll sync the PR tomorrow, and clean it up a bit :)

**Comment by ghost** [comment]
Synced with `master`. Updated commit message to add all the stuff I did.

With the inclusion of `.gitattributes` to normalize the project over multiply platforms, the `pom.xml` file is all red.

Ed1t: Can you test it? I updated the exe plugin, but I reside on OS X.

**Comment by luisantonioa** [comment]
Hmm the resulting jar is a lot bigger now... is that related to you updating the versions of the dependencies?

**Comment by ghost** [comment]
That is indeed the case it seems. With your rollback, it seems to suit the needs better.

**Pull request merged**
